---
root: true

plugins:
  - babel

env:
  node: true
  browser: true

parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: latest

extends:
  - 'airbnb-base'

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  no-console: 0
